name: flashcard-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi=0.96.1
  - uvicorn=0.20.0
  - python-multipart=0.0.5
  - pydantic=1.10.12
  - python-dotenv=1.0.0
  - mangum
  - pip
  - pip:
    - chromadb==0.3.23
    - groq==0.11.0
    - PyPDF2==3.0.1
